[build]
  base = "apps/web"
  command = "rm -rf node_modules && npx -y pnpm@9.15.3 install --no-frozen-lockfile && npx -y pnpm@9.15.3 run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
